server:
  context-path: /sbmexc
jdbc:
  driver: com.mysql.jdbc.Driver
  url: jdbc:mysql://localhost:3306/sbmexc?useUnicode=true&characterEncoding=utf8&useSSL=false
  username: root
  password: 123456

mybatis_config_file: mybatis-config.xml
mapper_path: /mapper/**.xml
entity_package: com.growing.sbmexc.entity

spring:
  profiles:
    active: prod



